### ISSUE TITLE
Consider static types

### ISSUE THREAD

**Issue by markfinger** [markfinger/alas#115]
Most of the changes currently being considered will probably require rewrites on most of the codebase. Might be a good time to try and slip some static analysis in to get around the refactoring pains and lack of test coverage.

I'm strongly inclined towards TypeScript, primarily because large swathes of the industry seem to be moving towards it, whereas Flow seems to be struggling to break out of React's shadow. Also, I have an inherent distrust for daemon processes (Flow).

**Comment by spalger** [comment]
I would also suggest Typescript. It has a massive collection of library types, first-class editor integrations, and Typescript 2.0 is coming soon which includes [features](https://github.com/Microsoft/TypeScript/pull/7140) that have previously set flow apart.

**Comment by markfinger** [comment]
Quickly ran into a number of blocks when attempting to wire in `immutable`. Only solutions seem to involve a ridiculous amount of boilerplate with getters+setters for every property.

Immutable data structures is something that I feel is much more important for a heavily async system than static types. That being said, this is still worth considering once the story for integrating immutable data and static types has improved.

**Comment by markfinger** [comment]
As a small aside, the editor integration (in webstorm, at least) for TS was pretty fantastic. I'd forgotten how handy static types can be :)
