### ISSUE TITLE
Use SQLite as a persistent cache layer

### ISSUE THREAD

**Issue by markfinger** [markfinger/alas#116]
Background: #87

Should switch to SQLite as the underpinning cache implementation. 

Easiest path would be adding sqlite as a backend for kv-cache and changing the pipeline to default to it.

**Comment by markfinger** [comment]
To reduce cache overhead for read misses, it's probably worth applying a `select key from cache` query during initialisation. This would allow us to no-op misses instantly.

**Comment by spalger** [comment]
have you considered leveldb?

**Comment by markfinger** [comment]
Just took a bit of a poke around, looks like it might offer better performance characteristics for writes. Most benchmarks I've seen place sqlite and leveldb roughly equivalent for random reads.

Both provide batching of operations, so you can get some massive wins over a simple FS abstraction.

Besides leveldb's faster writes, it doesn't seem to offer much that sqlite doesn't. Write-perf isn't too much of a concern as the current implementation runs them without blocking any build phases.

At this stage, I'm inclined towards sqlite simply because it's a more mature abstraction with more well-known quirks and issues.
