### ISSUE TITLE
160% processor usage?

### ISSUE THREAD

**Issue by spalger** [markfinger/alas#84]
Hey, finding unfort very interesting and would love to play around with it some more, but in an initial run of the example I'm seeing crazy high processor usage and the fans on my laptop cranking to full speed. Any idea what might be causing this?

**Comment by spalger** [comment]
Hmm, running from source seems to have fixed the problem...

**Comment by markfinger** [comment]
Strange. Might be the file watchers. Which OS are you on?

If it happens again, do you mind doing a CPU profile? The incantation I usually use is https://github.com/markfinger/profiling-node

You could probably start the profiler, start the build, then wait for it to finish a pass 

``` js
build.onCompleted(() => {
  // stop the profiler
});
```
